### ISSUE TITLE
Users can view a map of the USA.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/electionwinner#1]
# Motivation
We want to start on a quest to create a map of the USA that is fully interactive. 

# Task Implementation
- [x] Users can see a map of the USA on the page. 
- [x] Users can see the title of the Project
- [x] Users can see that the map is front and center.
