### ISSUE TITLE
User can click a side menu to more easily click smaller states

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/electionwinner#10]
# Motivation
Some states are smaller than others, so we want to make it easier for people to click on the small states. To do this, we'll be adding a feature on the right side of the US in order to better facilitate the small state selection. 

# Task implementation
- [x] Create an element to house the smaller states
- [x] Determine what states should be added to the side menu
- [x] Create elements for these new options in the side menu
- [x] Register event listeners for these options
- [x] Make sure that the events are registered properly with the states and that each click on the smaller menu also changes the color of the state on the map. 
- [x] Make sure that the events can also change the totals when adjusted through the side menu. 
- [x] Make sure that changing the map also changes the values on the side menu for votes. 

![screen shot 2017-06-19 at 9 56 53 am](https://user-images.githubusercontent.com/26865352/27296437-acec8bf4-54d5-11e7-8955-89934aa706a3.png)
