### ISSUE TITLE
User can see more historical elections.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/electionwinner#17]
# Motivation 
As an educational project, we want to be able to show people just how elections have unfolded since a very long time ago.

# Task Implementation
- [x] Implement Historical data back to 1964. 
- [x] Make sure that the total number of electoral votes are correct. 
- [x] Make sure that the numbers add up properly. 
![screen shot 2017-06-21 at 6 54 58 pm](https://user-images.githubusercontent.com/26865352/27413939-2c417d04-56b3-11e7-9ad7-3bc0d187dc1f.png)

**Comment by victormejia** [comment]
don't forget wirefames
