### ISSUE TITLE
User can slide a bar to see transition between years.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/electionwinner#19]
# Motivation
For those interested in seeing how elections have differed year by year, we want to see how they gradually transition. 

# Task Implementation
- [x] Create a sliding bar on the bottom of the map.
- [x] Create a button to "play" the sliding bar. 
- [x] Create Midpoints for each transition from year to year. 
- [x] Make sure the bar can be properly listened to
- [x] Make sure that the bar is able to record its value properly. 
- [x] Make sure that the bar is able to record midpoints properly. 
- [x] Make sure the transitions are correctly gotten to.
- [x] When pressing the "play" button, make sure that the animations are properly rendered. 
- [x] Implement a stop button for the animation when playing

# WireFrame
![screen shot 2017-06-21 at 7 01 16 pm](https://user-images.githubusercontent.com/26865352/27414116-2a4edf90-56b4-11e7-97e1-8903f785bf53.png)
