### ISSUE TITLE
User can now view the number of electoral votes per year.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/electionwinner#21]
# Motivation 
We want the user to be able to see the number of electoral votes for each state. 

# Task Implementation
- [x] Get the number of votes for the state accurately per year
- [x] Overlay the numbers over the SVG
- [x] Make sure that the numbers update with each map change. 

# WireFrame
![screen shot 2017-06-22 at 4 26 22 pm](https://user-images.githubusercontent.com/26865352/27460258-8f174d82-5767-11e7-8ef3-c16c84cf9065.png)
