### ISSUE TITLE
Deploy to Heroku

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/electionwinner#23]
# Motivation
We want to be able to let other people play around with this

# Task implementation
- [ ] Setup app.
- [ ] Ignore the files that don't need to be heard from.
- [ ] Set up heroku scripts.
- [ ] Make sure the file is running.
