### ISSUE TITLE
Bug fixes

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/electionwinner#25]
# Motivation
We discovered some issues on chrome, and we must fix it. 

# Task implementation
- [x] Simplify the codebase so that the browser isn't reliant on a fixed width
- [x] Make sure that the app works on any browser
- [x] Make sure that the top scoring bar does not flicker on animation
