### ISSUE TITLE
User can include a state in a winning combination.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/electionwinner#3]
# Motivation
Now that we have a map that we can see, we want to be able to interact with the map. The first task is to make sure that the map can be interacted with. 

# Task Implementation
- [x] Be able to get the element that contains a state.
- [x] Be able to assign an event listener when a state is acted upon.
- [x] Be able to click on one state and get a response
- [x] Be able to click on any state and get a response
- [x] Be able to cycle through the colors of the state when clicked
![screen shot 2017-06-13 at 2 34 11 pm](https://user-images.githubusercontent.com/26865352/27105716-6e03aaf6-5045-11e7-9b6e-5ad7defd935b.png)
