### ISSUE TITLE
Users can now see the total Electoral Votes for the states selected.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/electionwinner#5]
![screen shot 2017-06-14 at 9 59 24 am](https://user-images.githubusercontent.com/26865352/27144832-30724172-50e8-11e7-8c5b-2189dc54f8ef.png)
# Motivation
We want the user to see how effective their selected combination of states is. To do this, we want the user to see how many votes the combination of selected states would yield in that scenario. 

# Task Implementation
- [x] Be able to view scores
- [x] Be able to track the color and votes variables for each state
- [x] Have the totals be updated with each click
- [x] Be able to see the total being updated with each color change
- [x] Be able to notify the user that the combination of states selected for a color would yield a winning result
- [x] Be able to de-notify user when a winning result is changed such that the combination no longer results in a winning combination.
