### ISSUE TITLE
User can select a pre-set map from a menu.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/electionwinner#6]
# Motivation
We want the user to be able to select pre-made maps in order to facilitate the process to selecting a winning combination. Not only is this useful to analyze a historical result, but to also factor in states that may or may not be considered "in play". 

# Task Implementation
- [x] Create a Drop down menu element with the following options listed: 2016 Actual Result, 2016 Battleground States, 2016 Close States, 2012 Actual Result, 2012 Battleground States, 2020 Battleground States.
- [x] Create Variables that reflect the nature of said selected options
- [x] Be able to visually display the pre-set maps when selected on the drop-down menu
- [x] Be able to view the totals of each pre-set map selection
- [x] Be able to view to reset the maps when done selecting them.

# WireFrame
![screen shot 2017-06-15 at 9 41 12 am](https://user-images.githubusercontent.com/26865352/27192067-cfc349ee-51ae-11e7-860a-872be9d0c4e2.png)
