### ISSUE TITLE
User can visually see a metered view of the combination selected.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/electionwinner#7]
# Motivation

While being able to view the result is nice, we also want to be able to emphasize the point of winning 270 electoral votes. To do this, we will implement a bar that represents visually the total number of electoral votes each combination gets. 

# Task Implementation
- [x] Create a div that is 538 pixels long.
- [x] Create more divs, depending on the parties that have votes or not. 
- [x] Be able to access these elements in order to manipulate them.
- [x] Be able to visually see the meter change after each time a state is clicked, or when a pre-set map is used. 
- [x] Be able to also put in the physical number in the bar to reflect its length to the user. 
- [x] Implement animated flow. 
- [x] Fix Text Overflow on the meter

# Wireframe
![screen shot 2017-06-16 at 9 22 42 am](https://user-images.githubusercontent.com/26865352/27235374-67b6de66-5275-11e7-8e75-e79de9d07990.png)
