### ISSUE TITLE
User can download a selected result from the page.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/electionwinner#8]
# Motivation
Since electionwinner is a hypothetical type of website, we want users to be able to share their combinations to their friends and others whom may wish to discuss their combinations via social media or others. We will be attempting to rasterize the SVG image and then creating an implementation to allow users to download the results onto their file systems. 

# Task implementation
- [x] Grab the element of the SVG its current state.
- [x] Create a clickable button that describes itself to save the image. 
- [x] Manipulate the SVG in order to convert its data type into a PNG.
- [x] Create a button to allow users to save the current image as a PNG.
- [x] Make the Download UI look cool. 
![screen shot 2017-06-19 at 9 31 37 am](https://user-images.githubusercontent.com/26865352/27295544-261c2fb0-54d2-11e7-86a6-4b4705a9c0e4.png)
